### ISSUE TITLE
Landing Gear Issues

### ISSUE THREAD

**Issue by Tharunkumar-AR** [Stratosphere-Studios/777-300ER#12] opened 2022-01-15 22:40 UTC
### Bug Description

I faced a few issues with the landing gear: 

1. Looks pale/discolored. 
2. This might not be a bug, but the landing gears are not tilted.
3.  Rear landing gears are not extending fully.
4.  Landing Gear Flaps are not closing. 

### Version
 - OS: [e.g. Windows]
 - X-Plane Version [e.g. 11.50]
 - 777 Version [e.g. v1.0]

### To Reproduce
N/A

### Visual Reference
N/A

**IMPORTANT: Make sure you have read the readme instructions BEFORE you post this issue. If you still have the issue, please ensure you have filled out all entries above with CLEAR, CONCISE answers. If so, you may delete this message and post your issue. Deleting this messahe shows that you have read the readme!**

**Comment by zeta976** [comment] 2022-01-16 02:14
1. Main gear was reworked and it is being textured so it looks discolored. (Not a bug)
2. This might be an error with gear tilt code (@crazytimtimtim).
3. I don't completely understand what do you mean but it is probably another error with gear logic code.
4. Landing gear flaps haven't been animated. (Not a bug)
Note: Try to close the sim and open it again (don't just reload the aircraft) and see if the gear tilt is still not working.

**Comment by crazytimtimtim** [comment] 2022-01-18 15:56
Not really sure, last time I used it it worked correctly but I'll check again.

Also, I'm currently rewriting gear code so your gear tilt bug should be fixed as well soon.

**Comment by crazytimtimtim** [comment] 2022-02-18 02:20
Closing this issue as I haven't been able to reproduce it. Gear code has been rewritten.

**Closed by crazytimtimtim** 2022-02-18 02:20 UTC
Labels: bug
